emblen/apps/formulacion/urls.py
from django.urls import path

from apps.formulacion import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),

    path('partidas/', views.PartidaListView.as_view(), name='partidas'),
    path('partida/crear/', views.PartidaCreateView.as_view(), name='c_partida'),
    path('partida/<int:pk>/', views.PartidaView.as_view(), name='v_partida'),
    path('partida/<int:pk>/eliminar/', views.PartidaDeleteView.as_view(), name='e_partida'),

    path('departamento/crear/', views.DepartamentoCreateView.as_view(), name='c_departamento'),
    path('departamento/<int:pk>/', views.DepartamentoView.as_view(), name='v_departamento'),
    path('departamentos/', views.DepartamentoListView.as_view(), name='departamentos'),
    path('departamento/<int:pk>/eliminar/', views.DepartamentoDeleteView.as_view(), name='e_departamento'),
    
    path('unidades-ejecutoras/', views.UnidadEjecutoraListView.as_view(), name='unidades_ejecutoras'),
    path('unidad-ejecutora/crear/', views.UnidadEjecutoraCreateView.as_view(), name='c_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/', views.UnidadEjecutoraView.as_view(), name='v_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/eliminar/', views.UnidadEjecutoraDeleteView.as_view(), name='e_unidad_ejecutora'),

    path('centros-costos/', views.CentroCostoListView.as_view(), name='centros_costos'),
    path('centro-costo/crear/', views.CentroCostoCreateView.as_view(), name='c_centro_costo'),
    path('centro-costo/<int:pk>/', views.CentroCostoView.as_view(), name='v_centro_costo'),
    path('centro-costo/<int:pk>/eliminar/', views.CentroCostoDeleteView.as_view(), name='e_centro_costo'),

    path('programas/', views.ProgramaListView.as_view(), name='programas'),
    path('programa/<int:pk>/', views.ProgramaView.as_view(), name='v_programa'),
    path('programa/crear/', views.ProgramaCreateView.as_view(), name='c_programa'),
    path('programa/<int:pk>/eliminar/', views.ProgramaDeleteView.as_view(), name='e_programa'),

    path('acciones-especificas/', views.AccionEspecificaListView.as_view(), name='acciones_especificas'),
    path('accion-especifica/<int:pk>/', views.AccionEspecificaView.as_view(), name='v_accion_especifica'),
    path('accion-especifica/crear/', views.AccionEspecificaCreateView.as_view(), name='c_accion_especifica'),
    path('accion-especifica/<int:pk>/eliminar/', views.AccionEspecificaDeleteView.as_view(), name='e_accion_especifica'),

    path('estimacion/', views.EstimacionView.as_view(), name='estimacion'),
    path('estimacion/<int:pk>', views.Estimacion2View.as_view(), name='estimacion2'),
    path('estimacion/<int:pk>/eliminar/', views.EstimacionDeleteView.as_view(), name='e_estimacion'),

    path('acciones-internas/', views.AccionInternaListView.as_view(), name='acciones_internas'),
    path('accion-interna/<int:pk>/', views.AccionInternaView.as_view(), name='v_accion_interna'),
    path('accion-interna/crear/', views.AccionInternaCreateView.as_view(), name='c_accion_interna'),
    path('accion-interna/<int:pk>/eliminar/', views.AccionInternaDeleteView.as_view(), name='e_accion_interna'),


    path('partida-accion-interna/', views.PartidaAccionInternaView.as_view(), name='partida_accion_interna'),
    path('partida-accion-interna/<int:pk>', views.PartidaAccionInternaEspecificaView.as_view(), name='partida_accion_interna_especifica'),
    path('partida-accion-interna/<int:pk>/eliminar/', views.PartidaAccionInternaDeleteView.as_view(), name='e_partida_accion_interna'),

    path('ingresos/', views.IngresoListView.as_view(), name='ingresos'),
    path('ingreso/<int:pk>', views.IngresoView.as_view(), name='v_ingreso'),
    path('ingreso/crear/', views.IngresoCreateView.as_view(), name='c_ingreso'),
    path('ingreso/<int:pk>/eliminar/', views.IngresoDeleteView.as_view(), name='e_ingreso'),

    path('lineas-programas/', views.LineaProgramaListView.as_view(), name='lineas_programas'),
    path('linea-programa/<int:pk>/', views.LineaProgramaView.as_view(), name='v_linea_programa'),
    path('linea-programa/crear/', views.LineaProgramaCreateView.as_view(), name='c_linea_programa'),
    path('linea-programa/<int:pk>/eliminar/', views.LineaProgramaDeleteView.as_view(), name='e_linea_programa'),

    
    path('planes-desarrollos/', views.PlanDesarrolloListView.as_view(), name='planes_desarrollo'),
    path('plan-desarrollo/<int:pk>/', views.PlanDesarrolloView.as_view(), name='v_plan_desarrollo'),
    path('plan-desarrollo/', views.PlanDesarrolloCreateView.as_view(), name='c_plan_desarrollo'),
    path('plan-desarrollo/<int:pk>/eliminar/', views.PlanDesarrolloDeleteView.as_view(), name='e_plan_desarrollo'),

    path('ejercicios-presupuestarios/', views.EjercicioPresupuestarioListView.as_view(), name='ejercicios_presupuestarios'),
    path('ejercicio-presupuestario/<int:pk>/', views.EjercicioPresupuestarioView.as_view(), name='v_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/crear/', views.EjercicioPresupuestarioCreateView.as_view(), name='c_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/<int:pk>/eliminar/', views.EjercicioPresupuestarioDeleteView.as_view(), name='e_ejercicio_presupuestario'),
]


urlreports = [
    path('r/creditos-asigandos/', reports.CreditosAsignadosReport.as_view(), name='re_creditos_asigandos'),
]


urlpatterns += urlreports

emblen/emblen/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios import views

from django.conf.urls import handler404,handler500
from apps.usuarios.views import mi_error_404,mi_error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.usuarios.urls', 'apps.usuarios'), namespace="usuarios")),
    path('formulacion/', include(('apps.formulacion.urls', 'apps.formulacion'), namespace="formulacion")),
    path('planificacion/', include(('apps.planificacion.urls', 'apps.planificacion'), namespace="planificacion")),
    path('ejecucion/', include(('apps.ejecucion.urls', 'apps.ejecucion'), namespace="ejecucion")),
    path('contabilidad/', include(('apps.contabilidad.urls', 'apps.contabilidad'), namespace="contabilidad")),
    path('compras/', include(('apps.compras.urls', 'apps.compras'), namespace="compras")),
    path('tesoreria/', include(('apps.tesoreria.urls', 'apps.tesoreria'), namespace="tesoreria")),
]

handler404 = mi_error_404
handler500 = mi_error_500

emblen/apps/formulacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.functions import Substr
from django.db.models import Max

from apps.base.models import EmblenBaseModel

from apps.nucleo.models import Publicacion


class Sector(EmblenBaseModel):

    codigo = models.CharField(max_length=2)

    nombre = models.CharField(max_length=100)

    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Sectores"


class Dependencia(EmblenBaseModel):

    sector = models.ForeignKey(
        Sector,
        related_name="dependencias",
        on_delete=models.PROTECT
    )

    codigo = models.CharField(max_length=2)

    nombre = models.CharField(max_length=100)

    descripcion = models.TextField()

    politica = models.TextField()

    mision = models.TextField()

    vision = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Dependencias"


class Departamento(EmblenBaseModel):
    
    unidad_ejecutora = models.ForeignKey(
        "UnidadEjecutora",
        related_name="departamentos",
        on_delete=models.PROTECT,
    )

    codigo = models.CharField(max_length=14)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Departamentos"


class Estado(EmblenBaseModel):
    
    codigo = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Estados"


class Municipio(EmblenBaseModel):

    estado = models.ForeignKey(
        Estado,
        related_name="municipios",
        on_delete=models.PROTECT
    )

    codigo = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Municipios"


class Parroquia(EmblenBaseModel):

    municipio = models.ForeignKey(
        Municipio,
        related_name="parroquias",
        on_delete=models.PROTECT
    )

    codigo = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Parroquias"


class FuenteFinanciamiento(EmblenBaseModel):

    codigo = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)

    orden = models.IntegerField()

    externo = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Fuentes de Financiamientos"


class CentroCosto(EmblenBaseModel):

    NIVELES = {
        1: 1,
        2: 3
    }
    
    codigo = models.CharField(max_length=6,unique=True)

    nombre = models.CharField(max_length=100)

    nivel = models.IntegerField()

    def sin_ceros(self):
        """Retorna el codigo sin ceros a la derecha"""
        return self.codigo[0:self.NIVELES[self.nivel]]

    def siguientes(self):
        """Devuelve queryset de los centros de costo hijos del nivel siguiente"""
        
        debe_comenzar = self.sin_ceros() 
        siguiente_nivel = self.nivel + 1

        queryset = CentroCosto.objects.filter(
            nivel=siguiente_nivel,
            codigo__startswith=debe_comenzar,
        )

        return queryset

    class Meta:
        ordering = ('-creado',)
        verbose_name_plural = "Centros de Costos"

    def __str__(self):
        return self.codigo


class UnidadEjecutora(EmblenBaseModel):

    dependencia = models.ForeignKey(
        Dependencia,
        related_name="unidadejecutoras",
        on_delete=models.PROTECT
    )
    
    adscrito = models.ForeignKey(
        "UnidadEjecutora",
        related_name="unidadejecutoras",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )

    codigo_ente = models.CharField(max_length=10)

    codigo_secundario = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Unidades Ejecutoras"


class SectorDesarrollador(EmblenBaseModel):
    
    codigo = models.CharField(max_length=3)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Sectores Desarrolladores"


class UnidadMedida(EmblenBaseModel):
    
    codigo = models.CharField(max_length=5)

    nombre = models.CharField(max_length=100)

    dimension = models.IntegerField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Unidades de Medidas"


class TipoBeneficiario(EmblenBaseModel):
    
    codigo = models.CharField(max_length=5)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Tipos de Beneficiarios"


class PeriodoActualizacion(EmblenBaseModel):
    
    codigo = models.CharField(max_length=5)

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Periodos de Actualizacion"
 

class CondicionPrograma(EmblenBaseModel):
    
    codigo = models.CharField(max_length=5)

    nombre = models.CharField(max_length=100)  #Formulado - Banco de Proyectos

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Condiciones de los Programas"


class Programa(EmblenBaseModel):

    FEMENINO = 0
    MASCULINO = 1
    AMBOS = 2
    NO_DEFINIDO = 3

    SEXO_BENEFICIARIO = (
        (FEMENINO, "Femenino"),
        (MASCULINO, "Masculino"),
        (AMBOS, "Ambos"),
        (NO_DEFINIDO, "No Definido")
    )
    
    NIVEL = (
        (1, "Proyecto"),
        (2, "Acción Centralizada")
    )

    periodo_actualizacion = models.ForeignKey(
        PeriodoActualizacion,
        related_name="programas",
        on_delete=models.PROTECT
    )

    # Información Básica =====================================

    anio = models.CharField(max_length=4) #Debería tomarse automaticamente le año que esté con condición *Formulación*
    #                                       En la tabla EjercicioPresupuestario

    codigo = models.CharField(max_length=11)

    nivel = models.IntegerField(choices=NIVEL)

    detalle = models.TextField()

    condicion = models.ForeignKey(
        CondicionPrograma,
        related_name="programas",
        on_delete=models.PROTECT
    )

    estado = models.CharField(max_length=3, default="INI") #INI

    sector_desarrollador = models.ForeignKey(
        SectorDesarrollador,
        related_name="programas",
        on_delete=models.PROTECT
    )

    plan_inversion_social = models.BooleanField(default=False)

    inicio = models.DateField()

    fin = models.DateField()

    responsable = models.ForeignKey(
        Departamento,
        related_name="programas",
        on_delete=models.PROTECT
    )

    # Ubicación ==============================================

    extension_territorial = models.BooleanField(default=True)

    parroquia = models.ForeignKey(
        Parroquia,
        related_name="programas",
        on_delete=models.PROTECT
    )

    # Objetivos ============================================
    
    desarrollo_sostenible = models.TextField()

    estrategico = models.TextField()

    problematica = models.TextField()

    especifico = models.TextField()

    resumen = models.TextField()   

    # Resultado Esperados ==================================

    bien_servicio = models.TextField()

    unidad_medida = models.ForeignKey(
        UnidadMedida,
        related_name="programas",
        on_delete=models.PROTECT
    )

    indicador_situacion = models.TextField(null=True,blank=True)

    indicador_fuente = models.TextField(null=True,blank=True)

    indicador_formula = models.TextField(null=True,blank=True)

    indicador_objetivo = models.TextField(null=True,blank=True)

    # Distribución Meta Física Trimestral ===================

    trimestre_1 = models.DecimalField(max_digits=22,decimal_places=2)
    trimestre_2 = models.DecimalField(max_digits=22,decimal_places=2)
    trimestre_3 = models.DecimalField(max_digits=22,decimal_places=2)
    trimestre_4 = models.DecimalField(max_digits=22,decimal_places=2)
    
    # Beneficiarios ==========================================

    tipo_beneficiario = models.ForeignKey(
        TipoBeneficiario,
        related_name="programas",
        on_delete=models.PROTECT
    )

    sexo_beneficiario = models.IntegerField(
        "Sexo del Beneficiario", 
        choices=SEXO_BENEFICIARIO,
        default=AMBOS
    )

    beneficiario_masculino = models.IntegerField(null=True,blank=True)

    beneficiario_femenino = models.IntegerField(null=True,blank=True)

    beneficiario_total = models.IntegerField()
    
    # Empleos Generados =======================================

    directo_masculino = models.IntegerField()

    directo_femenino = models.IntegerField()
    
    indirecto_masculino = models.IntegerField()
    
    indirecto_femenino = models.IntegerField()

    # Porcentaje Avance ========================================

    ejecucion_fisica = models.FloatField()

    ejecucion_financiera = models.FloatField()

    # Fields de Ayuda =========================

    duracion = models.DurationField()

    contador = models.IntegerField(default=1)


    def gen_codigo(self):
        """Genera el codigo del Programa en instancia"""
        
        # Consulta donde se busca la dependencia
        dependencia = self.responsable.unidad_ejecutora.dependencia
        
        # Extraccion del codigo en cada modelo y nivel
        cod_sector = dependencia.sector.codigo
        cod_dependencia = dependencia.codigo
        cod_tipo = f"0{self.nivel}"

emblen/apps/formulacion/views/departamento.py
from django.views.generic import ListView

from apps.base.views import (
    EmblenPermissionsMixin,
    EmblenDeleteView,
    EmblenFormView
)

from apps.formulacion.models import Departamento
from apps.formulacion.forms import DepartamentoForm


class DepartamentoListView(EmblenPermissionsMixin, ListView):
    permissions = {"all": ("formulacion.view_departamento",)}
    template_name = "formulacion/departamentos.html"
    success_url = "formulacion:departamentos"
    queryset = Departamento.objects.all().order_by("codigo")
    paginate_by = 8
    

class DepartamentoCreateView(EmblenPermissionsMixin, EmblenFormView):
    permissions = {"all": ("formulacion.add_departamento",)}
    template_name = "formulacion/departamento.html"
    form_class = DepartamentoForm
    success_url = "formulacion:departamentos"


class DepartamentoView(EmblenPermissionsMixin, EmblenFormView):
    permissions = {"all": ("formulacion.view_departamento",)}
    template_name = "formulacion/departamento.html"
    form_class = DepartamentoForm
    update_form = True
    success_url = "formulacion:departamentos"


class DepartamentoDeleteView(EmblenPermissionsMixin, EmblenDeleteView):
    permissions = {"all": ("formulacion.delete_departamento",)}
    model = Departamento
    success_url = "formulacion:departamentos"

emblen/templates/formulacion/_menu.html
{% extends 'base/menu.html' %}

{% block options %}
<!-- Opciones del Menú -->
<li class="nav-item">
  <a id="m_organizacion" class="nav-link" href="#navbar-dashboards" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-dashboards">
    <i class="fas fa-sitemap text-primary"></i>
    <!-- <i class="fas fa-project-diagram"></i> -->
    <span class="nav-link-text">Organización Ppto.</span>
  </a>
  <div class="collapse" id="navbar-dashboards">
    <ul class="nav nav-sm flex-column">

      {% if perms.formulacion.view_departamento %}
      <li class="nav-item">
        <a href="{% url 'formulacion:unidades_ejecutoras' %}" class="nav-link" id="m_unidades_ejecutoras"> 
          <span class="sidenav-mini-icon"> UE </span>
          <span class="sidenav-normal"> Unidades Ejecutoras </span>
        </a>
      </li>
      {% endif %}
      
      {% if perms.formulacion.view_unidadejecutora %}
      <li class="nav-item">
        <a href="{% url 'formulacion:departamentos' %}" class="nav-link" id="m_despartamentos">
          <span class="sidenav-mini-icon"> DP </span>
          <span class="sidenav-normal"> Departamentos </span>
        </a>
      </li>
      {% endif %}

      {% if perms.formulacion.view_centrocosto %}
      <li class="nav-item">
        <a href="{% url 'formulacion:centros_costos' %}" class="nav-link" id="m_centros_costos">
          <span class="sidenav-mini-icon"> CC </span>
          <span class="sidenav-normal"> Centros Costos </span>
        </a>
      </li>
      {% endif %}

      {% if perms.formulacion.view_partida %}
      <li class="nav-item">
        <a href="{% url 'formulacion:partidas' %}" class="nav-link" id="m_partidas">
          <span class="sidenav-mini-icon"> PT </span>
          <span class="sidenav-normal"> Partidas </span>
        </a>
      </li>
      {% endif %}
           
    </ul>
  </div>
</li>

<li class="nav-item">
  <a id="m_Ejercicio" class="nav-link" href="#navbar-ejercicio" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-dashboards2">
    <i class="fas fa-balance-scale text-primary"></i>
    <!-- <i class="fas fa-gavel text-primary"></i> -->
    <span class="nav-link-text">Ejercicio Presupuestario</span>
  </a>
  <div class="collapse" id="navbar-ejercicio">
    <ul class="nav nav-sm flex-column">
        {% if perms.formulacion.view_ejerciciopresupuestario %}
        <li class="nav-item">
          <a href="{% url 'formulacion:ejercicios_presupuestarios' %}" class="nav-link" id="m_anio_ejercicios">
            <span class="sidenav-mini-icon"> EJR </span>
            <span class="sidenav-normal"> Años</span>
          </a>
        </li>
        {% endif %}
      </ul>
  </div>
</li>

<li class="nav-item">
  <a  id="m_Ingreso" class="nav-link" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-examples">
    <i class="fas fa-hand-holding-usd text-primary"></i>
    <span class="nav-link-text">Ingresos</span>
  </a>
  <div class="collapse" id="navbar-examples">
    <ul class="nav nav-sm flex-column">
      {% if perms.formulacion.view_partida %}
      <li class="nav-item">
        <a href="{% url 'formulacion:ingresos' %}" class="nav-link" id="m_ingreso_carga">
          <span class="sidenav-mini-icon"> CG </span>
          <span class="sidenav-normal"> Carga </span>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</li>

<li class="nav-item">
  <a id="m_cargaLey" class="nav-link" href="#navbar-dashboards2" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-dashboards2">
    <i class="fas fa-balance-scale text-primary"></i>
    <!-- <i class="fas fa-gavel text-primary"></i> -->
    <span class="nav-link-text">Gastos</span>
  </a>
  <div class="collapse" id="navbar-dashboards2">
    <ul class="nav nav-sm flex-column">

      
      {% if perms.formulacion.view_programa %}
      <li class="nav-item">
        <a href="{% url 'formulacion:programas' %}" class="nav-link"  id="m_programas">
          <span class="sidenav-mini-icon"> CP </span>
          <span class="sidenav-normal"> Categorías Programáticas </span>
        </a>
      </li>
      {% endif %}

      {% if perms.formulacion.view_accionespecifica %}
      <li class="nav-item">
        <a href="{% url 'formulacion:acciones_especificas' %}" class="nav-link" id="m_acc_especificas">
          <span class="sidenav-mini-icon"> AE </span>
          <span class="sidenav-normal"> Acciones Especificas </span>
        </a>
      </li>
      {% endif %}

      <!-- {% if perms.formulacion.view_estimacion %}
      <li class="nav-item">
        <a href="{% url 'formulacion:estimacion' %}" class="nav-link" id="m_estimaciones">
          <span class="sidenav-mini-icon"> E </span>
          <span class="sidenav-normal"> Estimaciones </span>
        </a>
      </li>
      {% endif %} -->

      {% if perms.formulacion.view_accioninterna %}
      <li class="nav-item">
        <a href="{% url 'formulacion:acciones_internas' %}" class="nav-link" id="m_acc_internas">
          <span class="sidenav-mini-icon"> AI </span>
          <span class="sidenav-normal"> Acciones Internas </span>
        </a>
      </li>
      {% endif %}

      <!-- {% if perms.formulacion.view_partidaaccioninterna %}
      <li class="nav-item">
        <a href="{% url 'formulacion:partida_accion_interna' %}" class="nav-link" id="m_partidas_acc_internas">
          <span class="sidenav-mini-icon"> PAI </span>
          <span class="sidenav-normal"> Partidas Acc. Internas </span>
        </a>
      </li>
      {% endif %} -->

    </ul>
  </div>
</li>


<li class="nav-item">
  <a id="m_reportes" class="nav-link" href="#navbar-tables" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-tables">
    <i class="far fa-file text-primary"></i>
    <span class="nav-link-text">Reportes</span>
  </a>
  <div class="collapse" id="navbar-tables">
    <ul class="nav nav-sm flex-column">
      <li class="nav-item">
        <a data-toggle="modal" data-target="#creditos-presupuestarios-asig" href="#" class="nav-link" id="m_r_formulacion">
          <span class="sidenav-mini-icon"> CPA </span>
          <span class="sidenav-normal"> Créditos Pre Asig </span>
        </a>
      </li>  
      <li class="nav-item">
        <a data-toggle="modal" data-target="#creditos-presupuestarios-asig" href="#" class="nav-link" id="m_r_formulacion">
          <span class="sidenav-mini-icon"> CP </span>
          <span class="sidenav-normal"> Categorías Programáticas </span>
        </a>
      </li>  
      <li class="nav-item">
          <li class="nav-item">
            <a class="nav-link" href="#navbar-tables2" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-tables2">
              <span class="sidenav-mini-icon"> F </span>
              <span class="sidenav-normal"> Formatos </span>
            </a>
            <div class="collapse" id="navbar-tables2">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a data-toggle="modal" data-target="#creditos-presupuestarios-asig" href="#" class="nav-link pl-4" id="m_r_formulacion">
                    <span class="sidenav-mini-icon"> PI </span>
                    <span class="sidenav-normal"> Presupuesto de Ingresos </span>
                  </a>
                </li>
                 
              </ul>
            </div>
          </li>
      </li>            
    </ul>
  </div>
</li>
<hr class="my-4">
{% endblock options %}

emblen/templates/formulacion/_steps.html
{% extends 'base/steps.html' %}

{% block menu %}
  {% include 'formulacion/_menu.html' %}  
{% endblock menu %}

{% block modal %}
  {% include 'formulacion/_modal.html' %}
{% endblock modal %}