emblen/apps/compras/urls.py
from django.urls import path

from apps.compras import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),
    path('documentos-pagar/', views.DocumentoPagarListView.as_view(), name='documentos_pagar'),
    path('documento-pagar/crear/', views.DocumentoPagarCreateView.as_view(), name='c_documento_pagar'),
    path('documento-pagar/<int:pk>/eliminar/', views.DocumentoPagarDeleteView.as_view(), name='e_documento_pagar'),

]

urlreports = [
    path('r/orden-compra/', reports.OrdenCompraReport.as_view(), name='re_orden_compra'),
]


urlpatterns += urlreports

emblen/apps/ejecucion/urls.py
from django.urls import path

from apps.ejecucion import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),

    # path('documentos-pagar/', views.DocumentoPagarListView.as_view(), name='documentos_pagar'),
    # path('documento-pagar/<int:pk>/', views.DocumentoPagarView.as_view(), name='v_documento_pagar'),
    # path('documento-pagar/crear/', views.DocumentoPagarCreateView.as_view(), name='c_documento_pagar'),
    # path('documento-pagar/<int:pk>/eliminar/', views.DocumentoPagarDeleteView.as_view(), name='e_documento_pagar'),

    path('ordenes-pagos/', views.OrdenPagoListView.as_view(), name='ordenes_pagos'),
    path('ordenes-pagos/<int:pk>/', views.OrdenPagoView.as_view(), name='v_orden_pago'),
    path('orden-pago/crear/', views.OrdenPagoCreateView.as_view(), name='c_orden_pago'), 
    path('orden-pago/<int:pk>/eliminar/', views.OrdenPagoDeleteView.as_view(), name='e_orden_pago'), 

]

urlreports = [
    path('r/orden-pago/', reports.OrdenPagoReport.as_view(), name='re_orden_pago'),
]


urlpatterns += urlreports

emblen/apps/formulacion/urls.py
from django.urls import path

from apps.formulacion import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),

    path('partidas/', views.PartidaListView.as_view(), name='partidas'),
    path('partida/crear/', views.PartidaCreateView.as_view(), name='c_partida'),
    path('partida/<int:pk>/', views.PartidaView.as_view(), name='v_partida'),
    path('partida/<int:pk>/eliminar/', views.PartidaDeleteView.as_view(), name='e_partida'),

    path('departamento/crear/', views.DepartamentoCreateView.as_view(), name='c_departamento'),
    path('departamento/<int:pk>/', views.DepartamentoView.as_view(), name='v_departamento'),
    path('departamentos/', views.DepartamentoListView.as_view(), name='departamentos'),
    path('departamento/<int:pk>/eliminar/', views.DepartamentoDeleteView.as_view(), name='e_departamento'),
    
    path('unidades-ejecutoras/', views.UnidadEjecutoraListView.as_view(), name='unidades_ejecutoras'),
    path('unidad-ejecutora/crear/', views.UnidadEjecutoraCreateView.as_view(), name='c_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/', views.UnidadEjecutoraView.as_view(), name='v_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/eliminar/', views.UnidadEjecutoraDeleteView.as_view(), name='e_unidad_ejecutora'),

    path('centros-costos/', views.CentroCostoListView.as_view(), name='centros_costos'),
    path('centro-costo/crear/', views.CentroCostoCreateView.as_view(), name='c_centro_costo'),
    path('centro-costo/<int:pk>/', views.CentroCostoView.as_view(), name='v_centro_costo'),
    path('centro-costo/<int:pk>/eliminar/', views.CentroCostoDeleteView.as_view(), name='e_centro_costo'),

    path('programas/', views.ProgramaListView.as_view(), name='programas'),
    path('programa/<int:pk>/', views.ProgramaView.as_view(), name='v_programa'),
    path('programa/crear/', views.ProgramaCreateView.as_view(), name='c_programa'),
    path('programa/<int:pk>/eliminar/', views.ProgramaDeleteView.as_view(), name='e_programa'),

    path('acciones-especificas/', views.AccionEspecificaListView.as_view(), name='acciones_especificas'),
    path('accion-especifica/<int:pk>/', views.AccionEspecificaView.as_view(), name='v_accion_especifica'),
    path('accion-especifica/crear/', views.AccionEspecificaCreateView.as_view(), name='c_accion_especifica'),
    path('accion-especifica/<int:pk>/eliminar/', views.AccionEspecificaDeleteView.as_view(), name='e_accion_especifica'),

    path('estimacion/', views.EstimacionView.as_view(), name='estimacion'),
    path('estimacion/<int:pk>', views.Estimacion2View.as_view(), name='estimacion2'),
    path('estimacion/<int:pk>/eliminar/', views.EstimacionDeleteView.as_view(), name='e_estimacion'),

    path('acciones-internas/', views.AccionInternaListView.as_view(), name='acciones_internas'),
    path('accion-interna/<int:pk>/', views.AccionInternaView.as_view(), name='v_accion_interna'),
    path('accion-interna/crear/', views.AccionInternaCreateView.as_view(), name='c_accion_interna'),
    path('accion-interna/<int:pk>/eliminar/', views.AccionInternaDeleteView.as_view(), name='e_accion_interna'),


    path('partida-accion-interna/', views.PartidaAccionInternaView.as_view(), name='partida_accion_interna'),
    path('partida-accion-interna/<int:pk>', views.PartidaAccionInternaEspecificaView.as_view(), name='partida_accion_interna_especifica'),
    path('partida-accion-interna/<int:pk>/eliminar/', views.PartidaAccionInternaDeleteView.as_view(), name='e_partida_accion_interna'),

    path('ingresos/', views.IngresoListView.as_view(), name='ingresos'),
    path('ingreso/<int:pk>', views.IngresoView.as_view(), name='v_ingreso'),
    path('ingreso/crear/', views.IngresoCreateView.as_view(), name='c_ingreso'),
    path('ingreso/<int:pk>/eliminar/', views.IngresoDeleteView.as_view(), name='e_ingreso'),

    path('lineas-programas/', views.LineaProgramaListView.as_view(), name='lineas_programas'),
    path('linea-programa/<int:pk>/', views.LineaProgramaView.as_view(), name='v_linea_programa'),
    path('linea-programa/crear/', views.LineaProgramaCreateView.as_view(), name='c_linea_programa'),
    path('linea-programa/<int:pk>/eliminar/', views.LineaProgramaDeleteView.as_view(), name='e_linea_programa'),

    
    path('planes-desarrollos/', views.PlanDesarrolloListView.as_view(), name='planes_desarrollo'),
    path('plan-desarrollo/<int:pk>/', views.PlanDesarrolloView.as_view(), name='v_plan_desarrollo'),
    path('plan-desarrollo/', views.PlanDesarrolloCreateView.as_view(), name='c_plan_desarrollo'),
    path('plan-desarrollo/<int:pk>/eliminar/', views.PlanDesarrolloDeleteView.as_view(), name='e_plan_desarrollo'),

    path('ejercicios-presupuestarios/', views.EjercicioPresupuestarioListView.as_view(), name='ejercicios_presupuestarios'),
    path('ejercicio-presupuestario/<int:pk>/', views.EjercicioPresupuestarioView.as_view(), name='v_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/crear/', views.EjercicioPresupuestarioCreateView.as_view(), name='c_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/<int:pk>/eliminar/', views.EjercicioPresupuestarioDeleteView.as_view(), name='e_ejercicio_presupuestario'),
]


urlreports = [
    path('r/creditos-asigandos/', reports.CreditosAsignadosReport.as_view(), name='re_creditos_asigandos'),
]


urlpatterns += urlreports

emblen/emblen/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios import views

from django.conf.urls import handler404,handler500
from apps.usuarios.views import mi_error_404,mi_error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.usuarios.urls', 'apps.usuarios'), namespace="usuarios")),
    path('formulacion/', include(('apps.formulacion.urls', 'apps.formulacion'), namespace="formulacion")),
    path('planificacion/', include(('apps.planificacion.urls', 'apps.planificacion'), namespace="planificacion")),
    path('ejecucion/', include(('apps.ejecucion.urls', 'apps.ejecucion'), namespace="ejecucion")),
    path('contabilidad/', include(('apps.contabilidad.urls', 'apps.contabilidad'), namespace="contabilidad")),
    path('compras/', include(('apps.compras.urls', 'apps.compras'), namespace="compras")),
    path('tesoreria/', include(('apps.tesoreria.urls', 'apps.tesoreria'), namespace="tesoreria")),
]

handler404 = mi_error_404
handler500 = mi_error_500

emblen/apps/ejecucion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.functions import Substr
from django.db.models import Max

from apps.base.models import EmblenBaseModel
from django.core.exceptions import NON_FIELD_ERRORS


from apps.usuarios.models import User

from apps.nucleo.models import MovimientoGasto, Publicacion

from apps.formulacion.models import (
    Departamento,
    FuenteFinanciamiento
)

from apps.contabilidad.models import AsientoContable


class TipoOrdenPago(EmblenBaseModel):
    """ se guardarán los Tipos de Ordenes de Pagos """
    #Directa Especial = todas comprometen y causan al ser generadas
    #Causados = Solo Causan y las orden de compra, servicio y materiales-suministros Compromenten
    #Fondo de Terceros = todas comprometen y causan al ser generadas

    codigo = models.CharField(max_length=3) #DE - CAU - FTR

    descripcion = models.CharField(max_length=100) #Directa Especial - Causados - Fondo de Terceros

    compromete = models.BooleanField(default=False)

    causa = models.BooleanField(default=True)

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = "Tipos de Ordenes de Pagos"


class ClaseOrdenPago(EmblenBaseModel):
    """ se guardarán las Clases de Ordenes de Pagos """
    #PRESTACIÓN DE SERVICIOS

    descripcion = models.CharField(max_length=100) #PRESTACIÓN DE SERVICIOS

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = "Clases de Ordenes de Pagos"


class OrdenPago(EmblenBaseModel):
    """ se guardarán las Ordenes de Pago creadas"""
    ELABORADA = 0
    VERIFICADA = 1
    ANULADA = 2
    PAGADA = 3
    REVERSADA = 4

    ESTATUS_ORDEN = (
        (ELABORADA, "Elaborada"),
        (VERIFICADA, "Verificada"),
        (ANULADA, "Anulada"),
        (PAGADA, "Pagada"),
        (REVERSADA, "Reversada")
    )

    anio = models.CharField(max_length=4) 

    orden_pago = models.IntegerField()
    #Por año se debe reiniciar
    
    tipo = models.ForeignKey(
        TipoOrdenPago,
        related_name="ordenes_pago",
        on_delete=models.PROTECT
    ) # Tipo de Orden de Pago
    
    clase = models.ForeignKey(
        ClaseOrdenPago,
        related_name="ordenes_pago",
        on_delete=models.PROTECT
    ) # Clases de Orden de Pago

    unidad_origen = models.ForeignKey(
        Departamento,
        related_name="ordenes_pagos",
        on_delete=models.PROTECT
    )

    fuente_financiamiento = models.ForeignKey(
        FuenteFinanciamiento,
        related_name="ordenes_pagos",
        on_delete=models.PROTECT
    )

    beneficiario = models.ForeignKey(
        "compras.Beneficiario",
        related_name="ordenes_pago",
        on_delete=models.PROTECT,
        null=True
    )

    documento_pagar = models.ForeignKey(
        "compras.DocumentoPagar",
        related_name="ordenes_pago",
        on_delete=models.PROTECT,
        null=True
    )

    valuacion_contrato = models.ForeignKey(
        "compras.ValuacionContrato",
        related_name="ordenes_pago",
        on_delete=models.PROTECT,
        null=True
    )

    anticipo_contrato = models.ForeignKey(
        "compras.AnticipoContrato",
        related_name="ordenes_pago",
        on_delete=models.PROTECT,
        null=True
    )

    descripcion = models.CharField(max_length=300) #Descripción Orden de Pago

    fecha = models.DateField() #fecha de creacion de orden de pago

    monto = models.DecimalField(max_digits=22,decimal_places=4) # Monto Total de la Orden

    saldo = models.DecimalField(max_digits=22,decimal_places=4) # Saldo pendiente por pagar del monto de la orden
    #al beneficiario sería el monto sin deducciones
    
    monto_deduciones = models.DecimalField(max_digits=22,decimal_places=4) # Monto de las deducciones ( IVA, RETENCIONES, ETC ) de la Orden
    
    saldo_deducciones = models.DecimalField(max_digits=22,decimal_places=4) #Saldo pendiente real por pagar de las deducciones
   
    estatus = models.IntegerField(
        "Estatus Orden", 
        choices=ESTATUS_ORDEN,
        default=ELABORADA
    )
    
    # comprobante = models.ForeignKey(
    #     Comprobante,
    #     related_name="ordenes_pago",
    #     on_delete=models.PROTECT
    # )

    # comprobante_reverso = models.ForeignKey(
    #     Comprobante,
    #     related_name="reverso_ordenes_pago",
    #     on_delete=models.PROTECT
    # )

    elaborador = models.ForeignKey(
        User,
        related_name="elaborador_ordenes_pago",
        on_delete=models.PROTECT
    )

    verificador = models.ForeignKey(
        User,
        related_name="verificador_ordenes_pago",
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )

    anulador = models.ForeignKey(
        User,
        related_name="anulador_ordenes_pago",
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )  

    reversor = models.ForeignKey(
        User,
        related_name="revisor_ordenes_pago",
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )    

    contador = models.IntegerField(default=1)

    def __str__(self):
        return str(self.orden_pago)

    def gen_rest_attrs(self):
        """
        Genera Atributos Restante del Objeto en Instancia.
        >> ("orden_pago", "contador")
        """
       
        result = OrdenPago.objects.aggregate(Max('contador')).get("contador__max")
        
        if result:
            self.contador = result + 1
            
        self.codigo = self.contador

        self.saldo = self.monto 
        
        self.saldo_deducciones = self.monto_deduciones

    class Meta:
        verbose_name_plural = "Ordenes de Pago"


class AfectacionPresupuestaria(EmblenBaseModel):
    """ 
    En este modelo se deben guardar los afectaciones
    que se le vayan haciendo al presupuesto con las OP
    """

    anio = models.CharField(max_length=4)

    fecha = models.DateField()
    
    periodo = models.CharField(max_length=2)

    numero = models.CharField(max_length=10)

    movimiento_gasto = models.ForeignKey(
        MovimientoGasto,
        related_name="afectaciones_presupuestarias",
        on_delete=models.PROTECT
    )

    orden_pago = models.ForeignKey(
        OrdenPago,
        related_name="afectaciones_presupuestarias",
        on_delete=models.PROTECT
    )

    asiento_contable = models.ForeignKey(
        AsientoContable,
        related_name="afectaciones_presupuestarias",
        on_delete=models.PROTECT
    ) 

    def __str__(self):
        return self.numero

    class Meta:
        verbose_name_plural = "Afectaciones Presupuestarias"


class AfectacionContrato(EmblenBaseModel):
    """ 
    En este modelo se deben guardar los afectaciones
    que se le vayan haciendo a un contrato con las OP
    """

    anio = models.CharField(max_length=4)

    fecha = models.DateField()
    
    periodo = models.CharField(max_length=2)

    numero = models.CharField(max_length=10)

    contrato_partida = models.ForeignKey(
        "compras.ContratoPartida",
        related_name="afectaciones_contratos",
        on_delete=models.PROTECT
    )

    orden_pago = models.ForeignKey(
        OrdenPago,
        related_name="afectaciones_contratos",
        on_delete=models.PROTECT
    )

    asiento_contable = models.ForeignKey(
        AsientoContable,
        related_name="afectaciones_contratos",
        on_delete=models.PROTECT
    ) 

    def __str__(self):
        return self.numero

    class Meta:
        verbose_name_plural = "Afectaciones a Contratos"

emblen/apps/formulacion/views/principal.py
from django.db.models import Max

from apps.base.views import EmblenView
from braces.views import LoginRequiredMixin

from apps.formulacion.models import (
    EjercicioPresupuestario,
    Programa,
    AccionEspecifica
)


class PrincipalView(LoginRequiredMixin, EmblenView):
    template_name = "formulacion/principal.html"
    
    def altget(self, request):
        anio_ejercicio = EjercicioPresupuestario.objects.filter(condicion=1)
        anio_formulacion = EjercicioPresupuestario.objects.filter(condicion=0)

        proyectos = Programa.objects.filter(nivel=1).count()
        acc_esp_proyectos = AccionEspecifica.objects.filter(programa__nivel = 1).count()

        acc_centralizadas = Programa.objects.filter(nivel=2).count()
        acc_esp_acc_centralizadas = AccionEspecifica.objects.filter(programa__nivel = 2).count()

        max_proyecto1 = Programa.objects.filter(
                nivel=1
            ).aggregate(Max('id'))

        max_proyecto = Programa.objects.filter(id = max_proyecto1['id__max'])

        max_especifica1 = Programa.objects.filter(
                nivel=2
            ).aggregate(Max('id'))

        max_especifica = Programa.objects.filter(id = max_especifica1['id__max'])

        anios = EjercicioPresupuestario.objects.filter(condicion__in=[0,1,2]).order_by("-anio")

        
        return {"anios": anios, 'anio_ejercicio': anio_ejercicio, 'anio_formulacion': anio_formulacion, 'proyectos': proyectos, 'acc_centralizadas': acc_centralizadas, 'acc_esp_proyectos': acc_esp_proyectos, 'acc_esp_acc_centralizadas': acc_esp_acc_centralizadas, 'max_proyecto': max_proyecto, 'max_especifica': max_especifica}

emblen/templates/ejecucion/_base.html
{% extends 'base/base.html' %}

{% block menu %}
  {% include 'ejecucion/_menu.html' %}  
{% endblock menu %}

{% block modal %}
  {% include 'ejecucion/_modal.html' %}  
{% endblock modal %}

emblen/templates/ejecucion/_modal.html
{% include 'ejecucion/r/orden_pago_V.html' %}

emblen/templates/ejecucion/_steps.html
{% extends 'base/steps.html' %}

{% block menu %}
  {% include 'ejecucion/_menu.html' %}  
{% endblock menu %}

{% block modal %}
  {% include 'ejecucion/_modal.html' %}
{% endblock modal %}

emblen/templates/ejecucion/crear_modificacion.html
{% extends 'ejecucion/_base.html' %}

{% load static %}

{% block head %}
  <style type="text/css">
    .form-control[readonly] {
      background-color: white!important;
    }
  </style>
{% endblock head %}

{% block title %} Crear Afectacion Presupuestaria {% endblock title %}

{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'ejecucion:principal' %}">
      Formulación
    </a>
  </li>

  <li class="breadcrumb-item">
    <a href="#">
      Afectacion Presupuestaria
    </a>
  </li>
{% endblock breadcrumb %}

{% block body %}
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Crear Afectación Presupuestaria</h3>
            </div>
            <div class="col text-right">
              <a href="#" class="btn btn-sm btn-primary" id="queryButton" url="{% url 'ejecucion:modificaciones' %}" token="{{ csrf_token }}" callback="true">
                Crear
              </a>
              {% for accion in acciones %}
              <a href="{% url 'formulacion:principal' %}" class="btn btn-sm btn-default">Cancelar</a>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="card-body">
          <h6 class="heading-small text-muted mb-4">Afectación Presupuestaria</h6>
          <div class="pl-lg-4">
            <div class="row">
            </div>
            <form method="POST" action="." id="form">
              {% csrf_token %}


              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_anio">Año</label>
                    {% for formulado in anio_ejercicio %}
                      <input type="text" id="id_anio" value="{{formulado.anio}}" readonly maxlength="4" name="anio" class="form-control queryInput" autocomplete="off">
                    {% endfor %}
                  </div>
                </div>

                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_documento_referenciado">Documento Referenciado</label>
                    <select class="form-control queryInput" data-toggle="select" id="id_documento_referenciado" name="documento_referenciado">
                      <option>--------------------</option>
                      {% for documento_referenciado in documento_referenciado %}
                        <option value="{{documento_referenciado.id}}">{{documento_referenciado.orden_pago}} - {{documento_referenciado.descripcion}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_partida_accioninterna">Seleccione Partida</label>
                    <select class="form-control queryInput" data-toggle="select" id="id_partida_accioninterna" name="partida_accioninterna">
                      <option>--------------------</option>
                      {% for partida_accioninterna in partidas %}
                        <option value="{{partida_accioninterna.id}}">{{partida_accioninterna.cuenta}} - {{partida_accioninterna.descripcion}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
              </div>

              <div class="row">

                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_numero">Número Correlativo</label>
                    <input type="text" placeholder="Ingrese Saldo" class="form-control queryInput" name="numero" id="id_numero">
                  </div>
                </div>

                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_numero">Tipo Modificación</label>
                    <input type="text" placeholder="Ingrese Saldo" class="form-control queryInput" name="tipo_modificacion" id="id_tipo_modificacion">
                  </div>
                </div>

              </div>

              <div class="row">

                
                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_numero">Descripción</label>
                    <input type="text" placeholder="Ingrese Saldo" class="form-control queryInput" name="descripcion" id="id_descripcion">
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_monto">Monto</label>
                    <input type="text" placeholder="Ingrese Saldo" class="form-control inputCurrency queryInputCurrency" name="monto" id="id_monto">
                  </div>
                </div>

                <div class="col">
                  <div class="form-group">
                    <label class="form-control-label" for="id_monto">Saldo</label>
                    <input type="text" placeholder="Ingrese Saldo" class="form-control inputCurrency queryInputCurrency" name="saldo" id="id_saldo">
                  </div>
                </div>

              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-header border-0">
          <h3 class="mb-0" style="display: inline;">Estimaciones de Acción Especifica </h3>
 
            <a href="javascript:document.location.reload();" title="Recargar Opciones" class="btn btn-sm btn-primary float-right" >
              <i class="fas fa-redo-alt"></i>
            </a>
        </div><!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="text-center">Acción Esp</th>
                <th scope="col" class="text-center" width="40%">Partida</th>
                <th scope="col" class="text-center">Año</th>
                <th scope="col" class="text-center" width="40%">Monto</th>
                <th scope="col"><i class="fas fa-cogs"></i> </th>
              </tr>
            </thead>
            <tbody class="list">
              {% for estimacion in estimacion %}
                <tr>
                  <th>{{estimacion.accion_especifica}}</th>
                  <th><input type="text" readonly value="{{ estimacion.partida }}" class="form-control input-tablas "></th>
                  <th class="text-center">{{estimacion.anio}}</th>
                  <th><input type="text" readonly value="{{ estimacion.monto }}" class="form-control input-tablas inputCurrency text-right"> </th>
                  <td class="text-right">
                    <a href="{% url 'formulacion:e_estimacion' estimacion.id %}"
                    class="btn btn-sm btn-default" title="Eliminar">
                      <i class="fas fa-trash"></i>
                    </a>

                  </td>
                </tr>
              {% empty %}
                <tr id="ninguna">
                  <th colspan="4">
                    No tiene Estimaciones
                  </th>
                </tr>                
              {% endfor %}
            </tbody>
          </table>
        </div>
        
        <div class="card-footer">
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

{% block script %}
  <script type="text/javascript">
    // HTML Objects
    // $("#id_anio").datepicker({
    //   format: "yyyy",
    //   viewMode: "years", 
    //   minViewMode: "years"
    // });
  </script>

  <script>

    var flag = true;
    function callbackFunction(response){
      if(flag){
        $('#ninguna').hide();
        flag = false;
      }

      let mod = response.modificacion;
      $('table > tbody:last-child').append(`
        <tr>
          <th>${mod.orden_pago}</th>
          <th><input type="text" readonly value="${mod.codigo_partida}" class="form-control input-tablas "></th>
          <td class="text-center">${mod.anio}</td>
          <td><input type="text" readonly value="${mod.monto}" class="form-control input-tablas inputCurrency text-right"> </td>
          <td class="text-right">
                    <a href="${mod.id}/eliminar"
                    class="btn btn-sm btn-default" title="Eliminar">
                      <i class="fas fa-trash"></i>
                    </a>

                  </td>
        </tr>
      `);
    }
  </script>
{% endblock script %}