emblen/apps/compras/urls.py
from django.urls import path

from apps.compras import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),
    path('documentos-pagar/', views.DocumentoPagarListView.as_view(), name='documentos_pagar'),
    path('documento-pagar/crear/', views.DocumentoPagarCreateView.as_view(), name='c_documento_pagar'),
    path('documento-pagar/<int:pk>/eliminar/', views.DocumentoPagarDeleteView.as_view(), name='e_documento_pagar'),

]

urlreports = [
    path('r/orden-compra/', reports.OrdenCompraReport.as_view(), name='re_orden_compra'),
]


urlpatterns += urlreports

emblen/apps/formulacion/urls.py
from django.urls import path

from apps.formulacion import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),

    path('partidas/', views.PartidaListView.as_view(), name='partidas'),
    path('partida/crear/', views.PartidaCreateView.as_view(), name='c_partida'),
    path('partida/<int:pk>/', views.PartidaView.as_view(), name='v_partida'),
    path('partida/<int:pk>/eliminar/', views.PartidaDeleteView.as_view(), name='e_partida'),

    path('departamento/crear/', views.DepartamentoCreateView.as_view(), name='c_departamento'),
    path('departamento/<int:pk>/', views.DepartamentoView.as_view(), name='v_departamento'),
    path('departamentos/', views.DepartamentoListView.as_view(), name='departamentos'),
    path('departamento/<int:pk>/eliminar/', views.DepartamentoDeleteView.as_view(), name='e_departamento'),
    
    path('unidades-ejecutoras/', views.UnidadEjecutoraListView.as_view(), name='unidades_ejecutoras'),
    path('unidad-ejecutora/crear/', views.UnidadEjecutoraCreateView.as_view(), name='c_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/', views.UnidadEjecutoraView.as_view(), name='v_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/eliminar/', views.UnidadEjecutoraDeleteView.as_view(), name='e_unidad_ejecutora'),

    path('centros-costos/', views.CentroCostoListView.as_view(), name='centros_costos'),
    path('centro-costo/crear/', views.CentroCostoCreateView.as_view(), name='c_centro_costo'),
    path('centro-costo/<int:pk>/', views.CentroCostoView.as_view(), name='v_centro_costo'),
    path('centro-costo/<int:pk>/eliminar/', views.CentroCostoDeleteView.as_view(), name='e_centro_costo'),

    path('programas/', views.ProgramaListView.as_view(), name='programas'),
    path('programa/<int:pk>/', views.ProgramaView.as_view(), name='v_programa'),
    path('programa/crear/', views.ProgramaCreateView.as_view(), name='c_programa'),
    path('programa/<int:pk>/eliminar/', views.ProgramaDeleteView.as_view(), name='e_programa'),

    path('acciones-especificas/', views.AccionEspecificaListView.as_view(), name='acciones_especificas'),
    path('accion-especifica/<int:pk>/', views.AccionEspecificaView.as_view(), name='v_accion_especifica'),
    path('accion-especifica/crear/', views.AccionEspecificaCreateView.as_view(), name='c_accion_especifica'),
    path('accion-especifica/<int:pk>/eliminar/', views.AccionEspecificaDeleteView.as_view(), name='e_accion_especifica'),

    path('estimacion/', views.EstimacionView.as_view(), name='estimacion'),
    path('estimacion/<int:pk>', views.Estimacion2View.as_view(), name='estimacion2'),
    path('estimacion/<int:pk>/eliminar/', views.EstimacionDeleteView.as_view(), name='e_estimacion'),

    path('acciones-internas/', views.AccionInternaListView.as_view(), name='acciones_internas'),
    path('accion-interna/<int:pk>/', views.AccionInternaView.as_view(), name='v_accion_interna'),
    path('accion-interna/crear/', views.AccionInternaCreateView.as_view(), name='c_accion_interna'),
    path('accion-interna/<int:pk>/eliminar/', views.AccionInternaDeleteView.as_view(), name='e_accion_interna'),


    path('partida-accion-interna/', views.PartidaAccionInternaView.as_view(), name='partida_accion_interna'),
    path('partida-accion-interna/<int:pk>', views.PartidaAccionInternaEspecificaView.as_view(), name='partida_accion_interna_especifica'),
    path('partida-accion-interna/<int:pk>/eliminar/', views.PartidaAccionInternaDeleteView.as_view(), name='e_partida_accion_interna'),

    path('ingresos/', views.IngresoListView.as_view(), name='ingresos'),
    path('ingreso/<int:pk>', views.IngresoView.as_view(), name='v_ingreso'),
    path('ingreso/crear/', views.IngresoCreateView.as_view(), name='c_ingreso'),
    path('ingreso/<int:pk>/eliminar/', views.IngresoDeleteView.as_view(), name='e_ingreso'),

    path('lineas-programas/', views.LineaProgramaListView.as_view(), name='lineas_programas'),
    path('linea-programa/<int:pk>/', views.LineaProgramaView.as_view(), name='v_linea_programa'),
    path('linea-programa/crear/', views.LineaProgramaCreateView.as_view(), name='c_linea_programa'),
    path('linea-programa/<int:pk>/eliminar/', views.LineaProgramaDeleteView.as_view(), name='e_linea_programa'),

    
    path('planes-desarrollos/', views.PlanDesarrolloListView.as_view(), name='planes_desarrollo'),
    path('plan-desarrollo/<int:pk>/', views.PlanDesarrolloView.as_view(), name='v_plan_desarrollo'),
    path('plan-desarrollo/', views.PlanDesarrolloCreateView.as_view(), name='c_plan_desarrollo'),
    path('plan-desarrollo/<int:pk>/eliminar/', views.PlanDesarrolloDeleteView.as_view(), name='e_plan_desarrollo'),

    path('ejercicios-presupuestarios/', views.EjercicioPresupuestarioListView.as_view(), name='ejercicios_presupuestarios'),
    path('ejercicio-presupuestario/<int:pk>/', views.EjercicioPresupuestarioView.as_view(), name='v_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/crear/', views.EjercicioPresupuestarioCreateView.as_view(), name='c_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/<int:pk>/eliminar/', views.EjercicioPresupuestarioDeleteView.as_view(), name='e_ejercicio_presupuestario'),
]


urlreports = [
    path('r/creditos-asigandos/', reports.CreditosAsignadosReport.as_view(), name='re_creditos_asigandos'),
]


urlpatterns += urlreports

emblen/emblen/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios import views

from django.conf.urls import handler404,handler500
from apps.usuarios.views import mi_error_404,mi_error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.usuarios.urls', 'apps.usuarios'), namespace="usuarios")),
    path('formulacion/', include(('apps.formulacion.urls', 'apps.formulacion'), namespace="formulacion")),
    path('planificacion/', include(('apps.planificacion.urls', 'apps.planificacion'), namespace="planificacion")),
    path('ejecucion/', include(('apps.ejecucion.urls', 'apps.ejecucion'), namespace="ejecucion")),
    path('contabilidad/', include(('apps.contabilidad.urls', 'apps.contabilidad'), namespace="contabilidad")),
    path('compras/', include(('apps.compras.urls', 'apps.compras'), namespace="compras")),
    path('tesoreria/', include(('apps.tesoreria.urls', 'apps.tesoreria'), namespace="tesoreria")),
]

handler404 = mi_error_404
handler500 = mi_error_500

emblen/apps/compras/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.functions import Substr
from django.db.models import Max

from apps.base.models import EmblenBaseModel
from django.core.exceptions import NON_FIELD_ERRORS


from apps.nucleo.models import MovimientoGasto

from apps.contabilidad.models import (
    CuentaContable
)

from apps.ejecucion.models import (
    OrdenPago
)

class TipoBeneficiario(EmblenBaseModel):
    """ se guardarán los Tipos de Beneficiarios """
        #Contratistas = CTT
        #Proveedores = PRV
        #Nomina = NMN
        #Arrendamiento = ARR
        #Donaciones = DON
        #Viaticos = VTC
        #Otras =  OTR como para servicios básicos

    abreviacion = models.CharField(max_length=3)

    descripcion = models.CharField(max_length=100)

    cuenta_contable = models.ForeignKey(
        CuentaContable,
        related_name="tipos_beneficiarios",
        on_delete=models.PROTECT
    ) #Id cuenta contable generado automático EJ: cuenta dependiendo el tipo 2.01.01.01.01.001

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = "Tipos de Beneficiarios"


class Beneficiario(EmblenBaseModel):
    """ se guardarán los beneficiario creados"""
    
    rif = models.CharField(max_length=12)
    # Sólo iniciando con J-24297146-5 """

    razon_social = models.CharField(max_length=100) # Nombre del ente

    siglas = models.CharField(max_length=10) # Siglas del ente

    direccion= models.CharField(max_length=500) # Dirección del ente

    telefono = models.CharField(max_length=13) #Teléfono del ente ej: 0414-419-6314

    correo = models.EmailField(max_length=254)

    tipo_beneficiario = models.ForeignKey(
        TipoBeneficiario,
        related_name="beneficiarios",
        on_delete=models.PROTECT
    )
    
    #Datos de inscripcion
    numero_inscripcion = models.IntegerField() #Correlativo en nuestro sistema diferencia con id es que este codigo puede que lo necesiten ingresar manualmente por alguna razón

    fecha_inscripcion = models.DateField()

    usuario_inscripcion = models.ForeignKey(
        User,
        related_name="beneficiarios",
        on_delete=models.PROTECT
    )

    #Datos de Registro del Ente
    numero_registro = models.CharField(max_length=12) # Creo que es un numero propio del contratista

    fecha_registro = models.DateField()

    capital = models.DecimalField(max_digits=22,decimal_places=4) #Solo aplica si es proveedor y contratista

    #Datos del representante del Ente
    representante = models.CharField(max_length=100) # Nombres y Apellidos #Solo aplica si es proveedor y contratista

    cedula_representante = models.CharField(max_length=12) # Sólo iniciando con J-24297146-5 #Solo aplica si es proveedor y contratista

    #Datos de beneficiario
    fecha_vigencia = models.DateField()

    cuenta_contable = models.ForeignKey(
        CuentaContable,
        related_name="cuenta_beneficiarios",
        on_delete=models.PROTECT
    ) #Id cuenta contable generada automáticamente apartir de las cuentas
    #20101020000000	PROVEEDORES - para Contratistas
        #Entonces la cuenta contable sería 201010200001 para el primer CONTRATISTA
    #20101010000000	Cuentas a pagar - para Proveedores
        #Entonces la cuenta contable sería 201010100002 para el primer PROVEEDOR

    cuenta_anticipo = models.ForeignKey(
        CuentaContable,
        related_name="anticipo_beneficiarios",
        on_delete=models.PROTECT
    ) #Id cuenta contable generada automáticamente apartir de la cuenta 10102070000000 (ANTICIPOS)
        # Entonces la cuenta anticipo sería 101020700001 para el primer CONTRATISTA
    #Sólo aplica para contratistas

    def __str__(self):
        # return  self.rif
        return '%s - %s' %(self.rif,self.razon_social) 

    class Meta:
        verbose_name_plural = "Beneficiarios"


class TipoDocumento(EmblenBaseModel):
    
    codigo = models.CharField(max_length=4)

    nombre = models.CharField(max_length=100)
    # 1 debe ser FACTURA codigo FACT
    # 2 debe ser RECIBO codigo RECB
    # 3 debe ser ORDEN DIRECTA ESPECIAL codigo ORDE
    # 4 debe ser ANTICIPIO codigo ANTI
    # 5 debe ser VALUACION codigo VALU

    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Tipos de Documentos"


class DocumentoPagar(EmblenBaseModel):
    """Documentos a Pagar en las ordenes de pago *FACTURAS* - *RECIBOS* - *ETC* """

    CREDITO = 1
    CONTADO = 2
    EFECTIVO = 3

    FORMA_PAGO = (
        (CREDITO, "Crédito"),
        (CONTADO, "Contado"),
        (EFECTIVO, "Efectivo")
    )

    anio = models.CharField(max_length=4) #AÑO EN EJERCICIO
        
    tipo_documento = models.ForeignKey(
        TipoDocumento,
        related_name="documentos_pagar",
        on_delete=models.PROTECT
    )

    numero = models.CharField(max_length=10)

    numero_control = models.CharField(max_length=10)

    fecha = models.DateField()

    monto_imponible = models.DecimalField(max_digits=22,decimal_places=4)

    monto_iva = models.DecimalField(max_digits=22,decimal_places=4)

    monto = models.DecimalField(max_digits=22,decimal_places=4)

    descripcion = models.CharField(max_length=100)

    forma_pago = models.IntegerField(
        choices=FORMA_PAGO,
        default=CREDITO
    )

    orden = models.ForeignKey(
        "Orden",
        related_name="documentos_pagar",
        on_delete=models.PROTECT,
        null=True
    )

    beneficiario = models.ForeignKey(
        Beneficiario,
        related_name="documentos_pagar",
        on_delete=models.PROTECT,
        null=True
    )


    def __str__(self):
        return self.numero

    class Meta:
        verbose_name_plural = "Documentos a Pagar"
        unique_together = (("numero", "anio", "beneficiario"),)


class DetalleDocumentoPagar(EmblenBaseModel):
    """Detalles de Documentos a Pagar - por ejemplos los item de una factura """
     
    documento_pagar = models.ForeignKey(
        DocumentoPagar,
        related_name="detalles_documentos_pagar",
        on_delete=models.PROTECT
    )

    item = models.IntegerField()

    denominacion = models.CharField(max_length=300)

    cantidad = models.IntegerField()

    precio_unitario = models.DecimalField(max_digits=22,decimal_places=4)

    total= models.DecimalField(max_digits=22,decimal_places=4) #multiplicacion de cantidad * precio_unitario

    contador = models.IntegerField(default=1)

    def __str__(self):
        return self.documento_pagar

    def gen_rest_attrs(self):
        """
        Genera Atributos Restante del Objeto en Instancia.
        >> ("item", "contador")
        """

        result = DetalleDocumentoPagar.objects.filter(
            documento_pagar=self.documento_pagar
        ).aggregate(Max('contador')).get("contador__max")

        if result:
            self.contador = result + 1

        self.item = self.contador

    class Meta:
        verbose_name_plural = "Detalles de Documentos a Pagar"


class TipoContrato(EmblenBaseModel):
    """ se guardarán los Tipos de contratos """
        #Servicios = CSE
        #Materiales y Suministros = CMS
        #Obras = COB

    codigo = models.CharField(max_length=3)

    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = "Tipos de Contratos"


class Contrato(EmblenBaseModel):
    """ se guardarán los contratos(-obras-, -servicios- y -materiales y suministros-) creados
    Nota: cuando el contrato es CSE o CMS son Contratos Marco porque los beneficiarios serán varios
    Para ellos se creará una tabla donde se lleve la relacion Contratos-Beneficiarios (VALIDAR que SOLO sean contratistas)
    Para los contratos de COB sólo debe haber un beneficiario
    Los COB Suelen tener Anticipos que es una orden de pago (otorgando una parte por adelantado al contratista)
    Los COB se cancelan en totalidad con VALUACIONES de 1 a N valuaciones (que sería ordenes de pago de valuaciones)

    Importante= cuando se crea un contrato marco se esta haciendo un pre-compromiso apartando toda la disponibilidad
    de una partida completa para ese contrato, por ende, debe haber un solo contrato marco por ejercicio para una
    partida presupuestaria.

    partida 402-0-0-1 |
    partida 402-0-0-2 | | pretenecen al contrato Nº 1
    partida 402-0-0-3 |

    partida 402-0-0-4 |
    partida 402-0-0-5 | | pretenecen al contrato Nº 2
    partida 402-0-0-6 |

    partida 402-0-0-1 |
    partida 402-0-0-7 | | pretenecen al contrato Nº 3 || Esto no es posible ya que tanto la partida que termina en 1 y 4
    partida 402-0-0-4 |    pertenecen a otro contrato marco


    """
    anio = models.CharField(max_length=4)

    codigo = models.CharField(max_length=6) # correlativo POR TIPO de contrato - Reinicia por año

    tipo_contrato = models.ForeignKey(
        TipoContrato,
        related_name="contratos",
        on_delete=models.PROTECT
    )

    fecha = models.DateField() #Fecha Creación del Contrato

    descripcion = models.CharField(max_length=300) #del compromiso

    monto = models.DecimalField(max_digits=22,decimal_places=4) #monto total del compromiso

    saldo = models.DecimalField(max_digits=22,decimal_places=4) #Monto que queda pendiente del compromiso

    monto_transito = models.DecimalField(max_digits=22,decimal_places=4) #Monto que queda en transito del compromiso

    cedula_responsable = models.CharField(max_length=12) # J-24297146-5 Cédula de quien está creando el contrato o del representante del contratista

    nombre_responsable = models.CharField(max_length=100)

    addendum = models.ForeignKey(
        "Contrato",
        related_name="contratos",
        on_delete=models.PROTECT,
        null = True,
        blank=True,

emblen/apps/compras/forms.py
from django import forms

from apps.compras.models import (
    TipoBeneficiario,
    Beneficiario,
    TipoDocumento,
    DocumentoPagar,
    DetalleDocumentoPagar,
    TipoContrato,
    Contrato,
    BeneficiarioContrato,
    ContratoPartida,
    TipoOrden,
    Orden
)


class TipoBeneficiarioForm(forms.ModelForm):
    class Meta:
        model = TipoBeneficiario
        fields = "__all__"


class BeneficiarioForm(forms.ModelForm):
    class Meta:
        model = Beneficiario
        fields = "__all__"


class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = "__all__"

class DocumentoPagarForm(forms.ModelForm):
    class Meta:
        model = DocumentoPagar
        exclude = ("compromiso",)

        

emblen/templates/compras/_base.html
{% extends 'base/base.html' %}

{% block menu %}
  {% include 'compras/_menu.html' %}  
{% endblock menu %}

{% block modal %}
  {% include 'compras/_modal.html' %}  
{% endblock modal %}

emblen/templates/compras/_modal.html
{% include 'compras/r/orden_compra_V.html' %}

emblen/templates/compras/documentos_pagar.html
{% extends 'formulacion/_base.html' %}

{% load static %}

{% block title %}
  Lista de Documentos a Pagar
{% endblock title %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'formulacion:principal' %}">Compras</a></li>
  <li class="breadcrumb-item"><a href="{% url 'formulacion:acciones_especificas' %}">Documentos a Pagar</a></li>
{% endblock breadcrumb %}

{% block body %}
<div class="row">
  <!-- Light table -->
  <div class="col">
    <div class="card">
      <!-- Card header -->
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col-6">
            {% if request.GET.programa %}
              {% for acc in page_obj %}
                {% if forloop.counter < 2 %}
                  <h3 class="mb-0">Documentos a Pagar de la Orden: {{ acc.programa }} </h3>
                {% endif %}
              {% endfor %}
            {% else %}
              <h3 class="mb-0">Documentos a Pagar </h3>
            {% endif %}

            
          </div>
          <div class="col-6 text-right">
            {% if request.GET.programa %}
                <a id="btn_partidaNew" href="" >
              </a>
            {% else %}
              <a id="btn_partidaNew" href="{% url 'compras:c_documento_pagar' %}" 
              class="btn btn-sm btn-primary">
                Crear Documentos a Pagar
              </a>            
            {% endif %}
          </div>
        </div>
      </div>
      <!-- Light table -->
      <div class="table-responsive" id="tablaPartidas">
        <table class="table align-items-center table-hover" >
          <thead class="thead-light">
            <tr>
              <th scope="col" class="sort text-center">Número</th>
              <th scope="col" class="sort text-center">Número control</th>
              <th scope="col" class="sort text-center">Beneficiario</th>
              <th scope="col" class="sort text-center" style="width:20%;">Descripción</th>
              <th scope="col" class="sort text-center">Monto Imponible</th>
              <th scope="col" class="sort text-center ">Iva</th>
              <th scope="col" class="sort text-center">Total</th>
              {% if perms.formulacion.delete_documentopagar %}
              <th scope="col" class="text-center" style="width:5%;"><i class="fas fa-cogs"></i></th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for doc in page_obj %}
              <tr>
                <th scope="row" class="nivel text-center">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <a href="{% url 'formulacion:v_accion_especifica' doc.id %}">
                        <span class="name mb-0 text-sm">{{ doc.numero }}</span>
                      </a>
                    </div>
                  </div>
                </th>
                <td class="text-center">
                  {{ doc.numero_control }}
                </td>
                <td class="text-center">
                  {{ doc.beneficiario.razon_social }}
                </td>
                <td class="text-center" >
                  <input type="text" class="form-control input-tablas" value='{{ doc.descripcion }}' readonly>
                  <!-- {{ doc.detalle|slice:"0:80" }} -->
                </td>                
                <td class="text-center">
                  <input type="text" readonly value="{{ doc.monto_imponible }}" class="form-control input-tablas inputCurrency text-right">
                </td>
                <td class="text-center">
                  <input type="text" readonly value="{{ doc.monto_iva }}" class="form-control input-tablas inputCurrency text-right">
                </td>
                <td class="text-center"> 
                  <input type="text" readonly value="{{ doc.monto }}" class="form-control input-tablas inputCurrency text-right">
                </td>
                {% if perms.formulacion.delete_accionespecifica %}
                <td class="text-right">
                  <a href="{% url 'compras:e_documento_pagar' doc.id %}"
                  class="btn btn-sm btn-default">
                    Eliminar
                  </a>
                </td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- Card footer -->
    
    {% if request.GET.programa %}

<div class="card-footer py-4">
  <nav aria-label="...">
    <ul class="pagination justify-content-end mb-0">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?programa={{request.GET.programa}};?page=1" tabindex="-1">
            <i class="fas fa-angle-double-left"></i>
            <span class="sr-only">first</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?programa={{request.GET.programa}};page={{ page_obj.previous_page_number }}" tabindex="-1">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
          </a>              
        </li>
      {% endif %}

      <li class="page-item active">
        <a class="page-link link-active" href="?programa={{request.GET.programa}};page=1" tabindex="-1">{{ page_obj.number }}</a>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?programa={{request.GET.programa}};page={{ page_obj.next_page_number }}">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">Next</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?programa={{request.GET.programa}};page={{ page_obj.paginator.num_pages }}">
            <i class="fas fa-angle-double-right"></i>
            <span class="sr-only">Last</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% else %}
  {% include 'base/_paginador.html' %}
{% endif %}

    </div>
  </div>
</div>
{% endblock body %}