emblen/apps/compras/urls.py
from django.urls import path

from apps.compras import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),
    path('documentos-pagar/', views.DocumentoPagarListView.as_view(), name='documentos_pagar'),
    path('documento-pagar/crear/', views.DocumentoPagarCreateView.as_view(), name='c_documento_pagar'),
    path('documento-pagar/<int:pk>/eliminar/', views.DocumentoPagarDeleteView.as_view(), name='e_documento_pagar'),

]

urlreports = [
    path('r/orden-compra/', reports.OrdenCompraReport.as_view(), name='re_orden_compra'),
]


urlpatterns += urlreports

emblen/apps/formulacion/urls.py
from django.urls import path

from apps.formulacion import views, reports

urlpatterns = [
    path('', views.PrincipalView.as_view(), name='principal'),

    path('partidas/', views.PartidaListView.as_view(), name='partidas'),
    path('partida/crear/', views.PartidaCreateView.as_view(), name='c_partida'),
    path('partida/<int:pk>/', views.PartidaView.as_view(), name='v_partida'),
    path('partida/<int:pk>/eliminar/', views.PartidaDeleteView.as_view(), name='e_partida'),

    path('departamento/crear/', views.DepartamentoCreateView.as_view(), name='c_departamento'),
    path('departamento/<int:pk>/', views.DepartamentoView.as_view(), name='v_departamento'),
    path('departamentos/', views.DepartamentoListView.as_view(), name='departamentos'),
    path('departamento/<int:pk>/eliminar/', views.DepartamentoDeleteView.as_view(), name='e_departamento'),
    
    path('unidades-ejecutoras/', views.UnidadEjecutoraListView.as_view(), name='unidades_ejecutoras'),
    path('unidad-ejecutora/crear/', views.UnidadEjecutoraCreateView.as_view(), name='c_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/', views.UnidadEjecutoraView.as_view(), name='v_unidad_ejecutora'),
    path('unidad-ejecutora/<int:pk>/eliminar/', views.UnidadEjecutoraDeleteView.as_view(), name='e_unidad_ejecutora'),

    path('centros-costos/', views.CentroCostoListView.as_view(), name='centros_costos'),
    path('centro-costo/crear/', views.CentroCostoCreateView.as_view(), name='c_centro_costo'),
    path('centro-costo/<int:pk>/', views.CentroCostoView.as_view(), name='v_centro_costo'),
    path('centro-costo/<int:pk>/eliminar/', views.CentroCostoDeleteView.as_view(), name='e_centro_costo'),

    path('programas/', views.ProgramaListView.as_view(), name='programas'),
    path('programa/<int:pk>/', views.ProgramaView.as_view(), name='v_programa'),
    path('programa/crear/', views.ProgramaCreateView.as_view(), name='c_programa'),
    path('programa/<int:pk>/eliminar/', views.ProgramaDeleteView.as_view(), name='e_programa'),

    path('acciones-especificas/', views.AccionEspecificaListView.as_view(), name='acciones_especificas'),
    path('accion-especifica/<int:pk>/', views.AccionEspecificaView.as_view(), name='v_accion_especifica'),
    path('accion-especifica/crear/', views.AccionEspecificaCreateView.as_view(), name='c_accion_especifica'),
    path('accion-especifica/<int:pk>/eliminar/', views.AccionEspecificaDeleteView.as_view(), name='e_accion_especifica'),

    path('estimacion/', views.EstimacionView.as_view(), name='estimacion'),
    path('estimacion/<int:pk>', views.Estimacion2View.as_view(), name='estimacion2'),
    path('estimacion/<int:pk>/eliminar/', views.EstimacionDeleteView.as_view(), name='e_estimacion'),

    path('acciones-internas/', views.AccionInternaListView.as_view(), name='acciones_internas'),
    path('accion-interna/<int:pk>/', views.AccionInternaView.as_view(), name='v_accion_interna'),
    path('accion-interna/crear/', views.AccionInternaCreateView.as_view(), name='c_accion_interna'),
    path('accion-interna/<int:pk>/eliminar/', views.AccionInternaDeleteView.as_view(), name='e_accion_interna'),


    path('partida-accion-interna/', views.PartidaAccionInternaView.as_view(), name='partida_accion_interna'),
    path('partida-accion-interna/<int:pk>', views.PartidaAccionInternaEspecificaView.as_view(), name='partida_accion_interna_especifica'),
    path('partida-accion-interna/<int:pk>/eliminar/', views.PartidaAccionInternaDeleteView.as_view(), name='e_partida_accion_interna'),

    path('ingresos/', views.IngresoListView.as_view(), name='ingresos'),
    path('ingreso/<int:pk>', views.IngresoView.as_view(), name='v_ingreso'),
    path('ingreso/crear/', views.IngresoCreateView.as_view(), name='c_ingreso'),
    path('ingreso/<int:pk>/eliminar/', views.IngresoDeleteView.as_view(), name='e_ingreso'),

    path('lineas-programas/', views.LineaProgramaListView.as_view(), name='lineas_programas'),
    path('linea-programa/<int:pk>/', views.LineaProgramaView.as_view(), name='v_linea_programa'),
    path('linea-programa/crear/', views.LineaProgramaCreateView.as_view(), name='c_linea_programa'),
    path('linea-programa/<int:pk>/eliminar/', views.LineaProgramaDeleteView.as_view(), name='e_linea_programa'),

    
    path('planes-desarrollos/', views.PlanDesarrolloListView.as_view(), name='planes_desarrollo'),
    path('plan-desarrollo/<int:pk>/', views.PlanDesarrolloView.as_view(), name='v_plan_desarrollo'),
    path('plan-desarrollo/', views.PlanDesarrolloCreateView.as_view(), name='c_plan_desarrollo'),
    path('plan-desarrollo/<int:pk>/eliminar/', views.PlanDesarrolloDeleteView.as_view(), name='e_plan_desarrollo'),

    path('ejercicios-presupuestarios/', views.EjercicioPresupuestarioListView.as_view(), name='ejercicios_presupuestarios'),
    path('ejercicio-presupuestario/<int:pk>/', views.EjercicioPresupuestarioView.as_view(), name='v_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/crear/', views.EjercicioPresupuestarioCreateView.as_view(), name='c_ejercicio_presupuestario'),
    path('ejercicio-presupuestario/<int:pk>/eliminar/', views.EjercicioPresupuestarioDeleteView.as_view(), name='e_ejercicio_presupuestario'),
]


urlreports = [
    path('r/creditos-asigandos/', reports.CreditosAsignadosReport.as_view(), name='re_creditos_asigandos'),
]


urlpatterns += urlreports

emblen/emblen/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios import views

from django.conf.urls import handler404,handler500
from apps.usuarios.views import mi_error_404,mi_error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.usuarios.urls', 'apps.usuarios'), namespace="usuarios")),
    path('formulacion/', include(('apps.formulacion.urls', 'apps.formulacion'), namespace="formulacion")),
    path('planificacion/', include(('apps.planificacion.urls', 'apps.planificacion'), namespace="planificacion")),
    path('ejecucion/', include(('apps.ejecucion.urls', 'apps.ejecucion'), namespace="ejecucion")),
    path('contabilidad/', include(('apps.contabilidad.urls', 'apps.contabilidad'), namespace="contabilidad")),
    path('compras/', include(('apps.compras.urls', 'apps.compras'), namespace="compras")),
    path('tesoreria/', include(('apps.tesoreria.urls', 'apps.tesoreria'), namespace="tesoreria")),
]

handler404 = mi_error_404
handler500 = mi_error_500

emblen/apps/compras/forms.py
from django import forms

from apps.compras.models import (
    TipoBeneficiario,
    Beneficiario,
    TipoDocumento,
    DocumentoPagar,
    DetalleDocumentoPagar,
    TipoContrato,
    Contrato,
    BeneficiarioContrato,
    ContratoPartida,
    TipoOrden,
    Orden
)


class TipoBeneficiarioForm(forms.ModelForm):
    class Meta:
        model = TipoBeneficiario
        fields = "__all__"


class BeneficiarioForm(forms.ModelForm):
    class Meta:
        model = Beneficiario
        fields = "__all__"


class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = "__all__"

class DocumentoPagarForm(forms.ModelForm):
    class Meta:
        model = DocumentoPagar
        exclude = ("compromiso",)

        

emblen/apps/compras/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, TemplateView
from django.http import JsonResponse, Http404
from django.db.models.functions import Substr
from braces.views import LoginRequiredMixin

from apps.base.views import (
    EmblenView,
    EmblenPermissionsMixin,
    EmblenDeleteView,
    EmblenFormView
)

from apps.compras.forms import (
    DocumentoPagarForm
)

from apps.compras.models import (
    DocumentoPagar
)


# ----- Compras -----

class PrincipalView(LoginRequiredMixin, TemplateView):
    template_name = "compras/principal.html"
    

class DocumentoPagarListView(EmblenPermissionsMixin, ListView):
    permissions = {"all": ("compras.view_documentopagar",)}
    template_name = "compras/documentos_pagar.html"
    success_url = "compras:documentos_pagar"
    queryset = DocumentoPagar.objects.all().order_by("numero")
    paginate_by = 8


class DocumentoPagarCreateView(EmblenPermissionsMixin, EmblenFormView):
    permissions = {"all": ("compras.add_documentopagar",)}
    template_name = "compras/crear_documento_pagar.html"
    form_class = DocumentoPagarForm
    success_url = "compras:documentos_pagar"

    def form_valid(self, form):
        documento_pagar = form.save(commit=False)
        # DocumentoPagar.gen_rest_attrs()
        return super().form_valid(documento_pagar)

class DocumentoPagarDeleteView(EmblenPermissionsMixin, EmblenDeleteView):
    permissions = {"all": ("compras.delete_documentopagar",)}
    model = DocumentoPagar
    success_url = "compras:documentos_pagar"

emblen/templates/compras/r/creditos_presupuestarios.html
{% extends 'base/reporte-base.html' %}

{% block title %}
    {% block rtitle %}
        Creditos Presupuestarios Asignados    
    {% endblock rtitle %}
{% endblock title %}

{% block subtitle %}
    Presupuesto de Gastos {{anio}}
{% endblock subtitle %}

{% block head %}
    <style type="text/css">
        .table .project td { 
            border-top: none;
            padding: 0.2em 0.5em;
            page-break-before: auto;
        }
    </style>
{% endblock head %}

{% block body %}
    {% for especifica in acc_especificas %}
        <div class="group-report">
            <!-- Proyecto -->
            <div class="row">
                <div class="col">
                    <table class="table">
                        <tbody class="project">
                            <tr>
                                <td><strong>Sector</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.codigo|slice:":2" }}
                                    </strong>
                                </td>
                                <td>
                                    {{ especifica.programa.responsable.unidad_ejecutora.dependencia.sector.descripcion }}
                                </td>
                            </tr>
                            <tr>
                                <td><strong>Dependencia</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.codigo|slice:"2:4" }}
                                    </strong>
                                </td>
                                <td>
                                {{ especifica.programa.responsable.unidad_ejecutora.dependencia.descripcion }}
                                </td>
                            </tr>
                            <tr>
                                <td><strong>Tipo</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.codigo|slice:"4:6" }}
                                    </strong>
                                </td>
                                {% if especifica.programa.nivel == 1 %}
                                    <td>Proyecto</td>
                                {% else %}
                                    <td>Acción Centralizada</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td><strong>Programa</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.codigo|slice:"6:8" }}
                                    </strong>
                                </td>
                                <td>
                                    {{ especifica.programa.detalle }}
                                </td>
                            </tr>
                            <tr>
                                <td class="text-nowrap"><strong>Acción Especifica</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.codigo|slice:"8:" }}
                                    </strong>
                                </td>
                                <td>
                                    {{ especifica.descripcion }}
                                </td>
                            </tr>
                            <tr>
                                <td class="text-nowrap"><strong>Centro de Costo</strong></td>
                                <td>
                                    <strong>
                                        {{ especifica.centro_costo.codigo }}
                                    </strong>
                                </td>
                                <td>
                                    {{ especifica.centro_costo.nombre }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Especifica -->
            <table class="table">
                <thead>
                <tr>
                    <th class="align-middle text-center">Pt</th>
                    <th class="align-middle text-center">Rmo</th>
                    <th class="align-middle text-center">Gen</th>
                    <th class="align-middle text-center">Esp</th>
                    <th class="align-middle text-center">Sub</th>
                    <th class="align-middle text-center">Aux</th>
                    <th class="align-middle text-center">Descripción de la Partida</th>
                    <th class="align-middle text-center">Acción Interna</th>
                    <th class="align-middle text-center">Fuente Fin</th>
                    <th class="align-middle text-center">Descripción de la Acción Interna</th>
                    <th class="align-middle text-center">Monto Asignado</th>
                </tr>
                </thead>
                <tbody>
                    {% for interna in especifica.acciones_internas.get_queryset %}
                        {% for rel in interna.partida_accioninternas.get_queryset %}
                            <tr>
                                <td class="text-center">{{ rel.partida.cuenta|slice:":1" }}</td>
                                <td class="text-center">{{ rel.partida.cuenta|slice:"1:3" }}</td>
                                <td class="text-center">{{ rel.partida.cuenta|slice:"3:5" }}</td>
                                <td class="text-center">{{ rel.partida.cuenta|slice:"5:7" }}</td>
                                <td class="text-center">{{ rel.partida.cuenta|slice:"7:9" }}</td>
                                <td class="text-center">{{ rel.partida.cuenta|slice:"9:" }}</td>
                                <td class="text-justify">{{ rel.partida.descripcion }}</td>
                                <td class="text-center">{{ rel.accion_interna.codigo }}</td>
                                <td class="text-center">{{ rel.accion_interna.fuente_financiamiento }}</td>
                                <td class="text-justify">{{ rel.accion_interna.descripcion }}</td>
                                <td class="text-right text-nowrap monto suma-monto" suma-id="{{especifica.id}}">{{ rel.mto_original }}</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                    <tr>
                        <td colspan="10" class="text-right">
                            <strong>
                                Monto Total:
                            </strong>
                        </td>
                        <td class="text-right monto" id="suma-id-{{especifica.id}}"></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <hr><!-- Divider -->
    {% endfor %}
{% endblock body %}

emblen/templates/compras/r/creditos_presupuestarios_V.html
<div class="modal fade" id="creditos-presupuestarios-asig" tabindex="-1" 
role="dialog" aria-labelledby="modal-form" aria-hidden="true">
  <div class="modal-dialog modal- modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div class="card bg-secondary shadow border-0">
          <div class="card-header bg-white">
            <div class="text-muted text-center mb-1">
              Creditos Presupuestarios Asignados
            </div>
          </div>
          <div class="card-body px-lg-5 py-lg-5">
            <div class="mb-1">
              Seleccione el Año a Consultar
            </div>
            <form method="post" action="{% url 'formulacion:re_creditos_asigandos' %}">
              {% csrf_token %}
              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <input type="text" id="id_anio_modal" maxlength="4" name="anio_modal"
                    class="form-control" autocomplete="off" placeholder="Seleccione Año...">
                  </div>
                </div>
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary my-4">Correr Reporte</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

emblen/templates/compras/r/orden_compra_V.html
<div class="modal fade" id="re_orden_compra" tabindex="-1" 
role="dialog" aria-labelledby="modal-form" aria-hidden="true">
  <div class="modal-dialog modal- modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div class="card bg-secondary shadow border-0">
          <div class="card-header bg-white">
            <div class="text-muted text-center mb-1">
              Orden de Compra
            </div>
          </div>
          <div class="card-body px-lg-5 py-lg-5">
            <div class="mb-1">
              Nº Orden de Compra
            </div>
            <form method="post" target="_blank" action="{% url 'compras:re_orden_compra' %}">
              {% csrf_token %}
              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <input type="text" id="id_anio_modal" maxlength="6" name="orden"
                    class="form-control" autocomplete="off" placeholder="EJ: 000092" required>
                  </div>
                </div>
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary my-4">Generar Orden</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>